import re
with open('plugins/chat_manager.py', 'r') as f:
    content = f.read()

# replace double \n\n generated by previous script with single \n
content = re.sub(r'\\n\\nMatches:', r'\\nMatches:', content)
with open('plugins/chat_manager.py', 'w') as f:
    f.write(content)
